# Generated by Django 5.2.5 on 2025-08-25 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('memberNumber', models.CharField(max_length=20, unique=True, verbose_name='Número de Socio')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('home', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilo')),
                ('memberRegistrationDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Alta')),
                ('memberDischargeDate', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('isActive', models.CharField(choices=[(1, 'Sí'), (0, 'No')], default=1, max_length=1, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de la Cuota')),
            ],
            options={
                'verbose_name': 'Configuraciones',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
