# Generated by Django 5.2.5 on 2025-08-25 11:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10, verbose_name='Monto'),
        ),
    ]
