# Generated by Django 5.2.5 on 2025-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='formNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Planilla'),
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=8, verbose_name='Mes de la Cuota'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Otro', 'Otro')], max_length=50, verbose_name='Método de Pago'),
        ),
    ]
