# Generated by Django 5.2.5 on 2025-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_payment_member_memberactivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberactivitylog',
            options={'verbose_name': 'Registro de Actividad del Socio', 'verbose_name_plural': 'Registros de Actividad de los Socios'},
        ),
        migrations.AlterField(
            model_name='member',
            name='isActive',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=1, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='memberactivitylog',
            name='activity',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], max_length=255),
        ),
    ]
