# Generated by Django 5.2.5 on 2025-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_memberactivitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='isActive',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=1, max_length=1, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='memberactivitylog',
            name='activity',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], max_length=1),
        ),
    ]
