# Generated by Django 5.2.5 on 2025-08-25 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_member_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='memberDischargeDate',
        ),
        migrations.AlterField(
            model_name='member',
            name='memberRegistrationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Admision'),
        ),
        migrations.AlterField(
            model_name='memberactivitylog',
            name='activity',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], max_length=1, verbose_name='Paso a:'),
        ),
        migrations.AlterField(
            model_name='memberactivitylog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='memberactivitylog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member', verbose_name='Socio'),
        ),
    ]
