# Generated by Django 5.2.5 on 2025-08-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_member_memberdischargedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberactivitylog',
            name='activity',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], max_length=1, verbose_name='Paso a'),
        ),
    ]
