# Generated by Django 5.2.5 on 2025-08-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_memberactivitylog_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Télefono Fijo'),
        ),
    ]
